@url_base = http://localhost:5003/api/item
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtIiwiZXhwIjoxNzUwOTA1NDI2fQ.zYB2gNN2q9RxhmLj4RyPj9syMba36sI7depSGBrhMnk
### Cadastrar categoria
POST {{url_base}}/cadastrar
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome" : "Bebidas",
    "categoriaId" : 1
}

### Listar categorias
GET {{url_base}}/listar
Authorization: Bearer {{token}}

### Listar itens por id
GET {{url_base}}/buscaritemporid/2
Authorization: Bearer {{token}}